var strings_en = {
	0x24 : "Hey, it's me!",
	0x25 : "Hi Conrad. You must be|wondering how you recorded|this message without|remembering it.",
	0x26 : "Good question, but it would|take too long to explain|and time is short, and if|you want to save your hide...",
	0x27 : " You must contact your old| friend Ian in New| Washington.",
	0x28 : "He'll explain it all there.|Good luck and watch your|back,because it's my life|you're playing with.",
	0x29 : "Slowly, the rays from the|regenerator re-implant the|memories in Conrad's brain.",
	0x2a : "The end-of-year thesis.",
	0x2b : "Glasses which measure|molecular density.",
	0x2c : "Individuals whose molecular|density is a thousand times|the norm.",
	0x2d : "Aliens mixed in with the|population.",
	0x2e : "My investigations have|attracted their attention.",
	0x2f : "I'm no longer safe.",
	0x30 : "I'm recording the hologram.",
	0x31 : "Then I save the contents of|my memory and send it to Ian.",
	0x37 : "OOOPS! A reunion.",
	0x38 : "Brothers I congratulate you.",
	0x39 : "Thanks to our knowledge,|the humans are now capable|of producing...",
	0x3a : "...the power which we need.",
	0x3b : "Soon,millions of our brother|warriors will be teleported...",
	0x3c : "and we will wipe out this|human vermin.",
	0x3f : "AAARGHHH!!!",
	0x41 : "A SPY... Throw the wretch|into the dungeons.",
	0x42 : "We'll|interrogate him later.",
	0x43 : "We have a winner! Allow me to|present Conrad.",
	0x44 : "My dear Conrad,TITAN TRAVEL|is happy to award you this|superb journey to Earth.",
	0x45 : "Some hours later, Conrad|boards the \"Star Providence\"|-destination: EARTH."
};
var strings_fr = {
	0x24 : "EH, MAIS C'EST MOI!",
	0x25 : "SALUT CONRAD! TU TE DEMANDES|SUREMENT COMMENT TU AS PU|ENREGISTRER CE MESSAGE SANS|T'EN SOUVENIR.",
	0x26 : "BONNE QUESTION MAIS CE SERAIT|TROP LONG A EXPLIQUER CAR LE|TEMPS PRESSE ET SI TU TIENS|A TA PEAU...",
	0x27 : "IL FAUT QUE TU|CONTACTES TON VIEIL AMI IAN A|NEW WASHINGTON.",
	0x28 : "LA, IL T'EXPLIQUERA TOUT.|BONNE CHANCE ET FAIS GAFFE|PARCE QUE C'EST MA PEAU QUE|TU VAS JOUER.",
	0x29 : "LENTEMENT, LE FAISCEAU DU|REGENERATEUR REGRAVE LES|SOUVENIRS DANS LA MEMOIRE|DE CONRAD.",
	0x2a : "LA THESE DE FIN D'ETUDES.",
	0x2b : "DES LUNETTES QUI MESURENT LA|DENSITE MOLECULAIRE.",
	0x2c : "DES INDIVIDUS DONT LA DENSITE|MOLECULAIRE EST MILLE FOIS|SUPERIEURE A LA NORMALE.",
	0x2d : "DES EXTRA-TERRESTRES|DISSIMULES PARMI|LA POPULATION.",
	0x2e : "MES RECHERCHES ONT ATTIRE|LEUR ATTENTION.",
	0x2f : "JE NE SUIS PLUS EN SECURITE.",
	0x30 : "J'ENREGISTRE L'HOLOGRAMME.",
	0x31 : "PUIS JE SAUVEGARDE LE CONTENU|DE MA MEMOIRE|ET JE L'EXPEDIE A IAN.",
	0x37 : "OOPS! UNE REUNION.",
	0x38 : "MES FRERES,JE VOUS FELICITE.",
	0x39 : "GRACE A NOTRE SAVOIR,|LES HUMAINS SONT MAINTENANT|CAPABLES DE PRODUIRE...",
	0x3a : "...L'ENERGIE DONT NOUS AVONS|BESOIN.",
	0x3b : "BIENTOT DES MILLIONS DE|FRERES GUERRIERS POURRONT|ETRE TELEPORTES...",
	0x3c : "ET NOUS|ECRASERONS CETTE VERMINE|HUMAINE.",
	0x3f : "AAAAHHH",
	0x41 : "EUH..SALUT,JE NE FAIS QUE|PASSER.",
	0x42 : "UN ESPION... METTEZ CE|MISERABLE AU CACHOT. NOUS|L'INTERROGERONS PLUS TARD.",
	0x43 : "C'EST UN GAGNANT! LAISSEZ-MOI|VOUS PRESENTER CONRAD LE|GRAND VAINQUEUR DE CE SOIR.",
	0x44 : "CHER CONRAD, LE TITAN TRAVEL|A LE PLAISIR DE VOUS OFFRIR CE|SUPERBE VOYAGE POUR LA TERRE.",
	0x45 : "QUELQUES HEURES PLUS TARD,|CONRAD EMBARQUE SUR LE \"STAR|PROVIDENCE\",DIRECTION:TERRE."
};
